server:
  port: 8081   # 项目管理模块服务端口，你可以按需调整

spring:
  application:
    name: code-helper-project

  datasource:
    url: jdbc:postgresql://localhost:5432/code_helper
    username: postgres         # 替换成你自己的数据库用户名
    password: Kk778899!    # 替换为你的密码
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none           # 我们已经在 Navicat 建好表，这里不用自动建表
    show-sql: true             # 开发期可以打开
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect